apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-devops-tools
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MarekSadlowski/istio-test.git
    targetRevision: HEAD
    directory:
      recurse: true
    path: istio-devops-tools
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: false
      prune: false
